[project]
name = "streamlit-sales-suite"
version = "0.2.0"
description = "Streamlit Sales Suite"
authors = [
    {name = "Daniel Bazo Correa", email = "none@none.com"},
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Topic :: Software Development",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "fastexcel==0.20.2",
    "openpyxl==3.1.5",
    "plotly==6.8.0",
    "polars==1.42.1",
    "streamlit==1.60.0",
]

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { git = { commit = true } }]

[dependency-groups]
pipeline = [
    "bandit==1.9.4",
    "complexipy==6.2.0",
    "mypy==2.3.1",
    "pytest==9.1.1",
    "ruff==0.16.0",
    "isort==8.0.1",
    "pre-commit==4.6.1",
]

[tool.ruff]
line-length = 88
indent-width = 4
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I"]
ignore = ["E203"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
line-ending = "auto"
docstring-code-format = true

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
force-to-top = ["src"]

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
exclude = [
    "^(build|dist|venv)",
    ".venv/"
]
cache_dir = "/dev/null"

[tool.isort]
profile = "black"
known_first_party = ["src"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
import_heading_stdlib = "Standard libraries"
import_heading_thirdparty = "3pps"
import_heading_firstparty = "Own modules"
import_heading_localfolder = "Own modules"
line_length = 88
include_trailing_comma = true
combine_as_imports = true
skip_glob = [".venv/*"]
