[project]
name = "src"
version = "0.1.0"
description = "Streamlit Sales Suite"
authors = [
    {name = "Daniel Bazo",email = "nothing@nothing.com"}
]
license = "LICENSE"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "complexipy (>=1.2.0,<2.0.0)",
    "bandit[toml] (>=1.8.2,<2.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "numpy (>=2.2.2,<3.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "streamlit (>=1.42.0,<2.0.0)",
    "matplotlib (>=3.10.0,<4.0.0)",
]
package-mode = false

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-timeout = "^2.3.1"

[tool.poetry.group.lint.dependencies]
black = "^24.10.0"
flake8 = "^7.1.1"
mypy = "^1.14.1"
typing-extensions = "^4.12.2"
types-requests = "^2.32.0.20241016"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 89
skip-string-normalization = false

[tool.bandit]
exclude = ["src/tests/"]
skips = ["B101"]