name: Setup Python Environment and uv
description: Setup Python, uv, and dependencies for the project

inputs:
  src-python-version:
    description: "Python version to set up for the project"
    required: true

runs:
  using: composite
  steps:
    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.10.2"
        python-version: ${{ inputs.src-python-version }}
        enable-cache: true

    - name: Install dependencies with uv
      shell: bash
      run: |
        uv sync --all-extras --all-groups

    - name: Verify uv and environment
      shell: bash
      run: |
        uv --version
        uv venv list
        uv run python --version
