name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

# Set up environment variables
env:
  # Folder where the project code is located
  SRC_PROJECT_FOLDER: "src"
  # Folder where test files are located
  SRC_PROJECT_TESTS: "tests"
  # Python version to use
  SRC_PYTHON_VERSION: "3.11"

# Define jobs in this workflow
jobs:
  setup-lint-test:
    name: Setup, Lint, Test, and Secure Code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python & Install Dependencies
        uses: ./.github/actions/setup-python-env
        with:
          src-python-version: ${{ matrix.python-version }}
          dependencies: "pipeline"

      - name: Lint Code (Black, Mypy, Flake8, Pylint, Complexipy)
        uses: ./.github/actions/lint-code
        with:
          src-project-folder: ${{ env.SRC_PROJECT_FOLDER }}

      - name: Run Tests with Pytest
        uses: ./.github/actions/test-code
        with:
          src-project-folder: ${{ env.SRC_PROJECT_FOLDER }}
          src-tests-folder: ${{ env.SRC_PROJECT_TESTS }}

      - name: Run Bandit Security Scan
        uses: ./.github/actions/security
        with:
          src-project-folder: ${{ env.SRC_PROJECT_FOLDER }}
          src-exclude: ${{ env.SRC_PROJECT_TESTS }}
